docs(README): Replace newlib with musl
Building with Newlib results in an error:

```
 E  /usr/bin/ld: [...]/.unikraft/build/libcontext.o: in function `ukarch_tls_area_init':
 E  [...]/.unikraft/unikraft/arch/x86/x86_64/tls.c:201: undefined reference to `ukarch_tls_tcb_init'
```

There is an issue with Newlib. Until this is fixed, there are two
approaches:

i) use Musl
b) remove the libc dependency altogether

Since Musl is the default Unikraft libc, use that. Replace `newlib` with
`musl` in the recommended contents for `Kraftfile`.

Signed-off-by: Razvan Deaconescu <razvand@unikraft.io>